# Generated by Django 3.2.7 on 2021-09-21 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='release_date',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='album',
            name='star_num',
            field=models.IntegerField(choices=[(1, 'Wrost'), (2, 'Bad'), (3, 'Not Bad'), (4, 'Good'), (5, 'Excellent!')], default=None),
        ),
        migrations.AlterField(
            model_name='album',
            name='artist',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='first_app.musician'),
        ),
    ]
