# Generated by Django 3.2.7 on 2021-10-08 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_auto_20210921_2320'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='album',
            table='Album',
        ),
        migrations.AlterModelTable(
            name='musician',
            table='Musician',
        ),
    ]
